//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ManagementPackCatalog.Admin.UI {
    
    
    public partial class _Default {
        
        /// <summary>
        /// MainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm MainForm;
        
        /// <summary>
        /// MainTabStrip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTabStrip MainTabStrip;
        
        /// <summary>
        /// MainMultiPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadMultiPage MainMultiPage;
        
        /// <summary>
        /// EmptyPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView EmptyPage;
        
        /// <summary>
        /// CategoryCreate_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView CategoryCreate_Page;
        
        /// <summary>
        /// CategoryCreate_TechnologyName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryCreate_TechnologyName_TextBox;
        
        /// <summary>
        /// CategoryCreate_TechnologyName_DropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox CategoryCreate_TechnologyName_DropDown;
        
        /// <summary>
        /// CategoryCreate_ProductName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryCreate_ProductName_TextBox;
        
        /// <summary>
        /// CategoryCreate_ProductName_DropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox CategoryCreate_ProductName_DropDown;
        
        /// <summary>
        /// CategoryCreate_LanguagePack_CheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CategoryCreate_LanguagePack_CheckBox;
        
        /// <summary>
        /// CategoryCreate_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CategoryCreate_Status;
        
        /// <summary>
        /// CategoryEdit_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView CategoryEdit_Page;
        
        /// <summary>
        /// CategoryEdit_Existing_TreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTreeView CategoryEdit_Existing_TreeView;
        
        /// <summary>
        /// CategoryEdit_CategoryId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryEdit_CategoryId_TextBox;
        
        /// <summary>
        /// CategoryEdit_ParentCategoryId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryEdit_ParentCategoryId_TextBox;
        
        /// <summary>
        /// CategoryEdit_DisplayName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryEdit_DisplayName_TextBox;
        
        /// <summary>
        /// CategoryEdit_Description_TextArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea CategoryEdit_Description_TextArea;
        
        /// <summary>
        /// CategoryEdit_GuideUriText_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryEdit_GuideUriText_TextBox;
        
        /// <summary>
        /// CategoryEdit_GuideUriLink_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryEdit_GuideUriLink_TextBox;
        
        /// <summary>
        /// CategoryEdit_Published_CheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CategoryEdit_Published_CheckBox;
        
        /// <summary>
        /// CategoryEdit_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryEdit_Submit_Button;
        
        /// <summary>
        /// CategoryEdit_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CategoryEdit_Status;
        
        /// <summary>
        /// CategoryAssociate_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView CategoryAssociate_Page;
        
        /// <summary>
        /// CategoryAssociate_Existing_TreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTreeView CategoryAssociate_Existing_TreeView;
        
        /// <summary>
        /// CategoryAssociate_CategoryId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssociate_CategoryId_TextBox;
        
        /// <summary>
        /// CategoryAssociate_ParentId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssociate_ParentId_TextBox;
        
        /// <summary>
        /// CategoryAssociate_DisplayName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssociate_DisplayName_TextBox;
        
        /// <summary>
        /// CategoryAssociate_Associated_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox CategoryAssociate_Associated_ComboBox;
        
        /// <summary>
        /// CategoryAssociate_UnAssociate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryAssociate_UnAssociate_Button;
        
        /// <summary>
        /// CategoryAssociate_UnAssociated_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox CategoryAssociate_UnAssociated_ComboBox;
        
        /// <summary>
        /// CategoryAssociate_Associate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryAssociate_Associate_Button;
        
        /// <summary>
        /// CategoryAssociate_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CategoryAssociate_Status;
        
        /// <summary>
        /// CategoryAssignMps_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView CategoryAssignMps_Page;
        
        /// <summary>
        /// CategoryAssignMps_Existing_Category_TreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTreeView CategoryAssignMps_Existing_Category_TreeView;
        
        /// <summary>
        /// CategoryAssignMps_Category_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Category_Id_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Category_ParentId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Category_ParentId_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Category_DisplayName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Category_DisplayName_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Existing_Assigned_ManagementPacks_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid CategoryAssignMps_Existing_Assigned_ManagementPacks_Grid;
        
        /// <summary>
        /// CategoryAssignMps_Assigned_ManagementPacks_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Assigned_ManagementPacks_Id_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Assigned_ManagementPacks_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Assigned_ManagementPacks_SystemName_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Assigned_ManagementPacks_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Assigned_ManagementPacks_PublicKey_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_Assigned_ManagementPacks_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_Assigned_ManagementPacks_Version_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_RemoveMp_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryAssignMps_RemoveMp_Button;
        
        /// <summary>
        /// CategoryAssignMps_Existing_UnAssigned_ManagementPacks_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid CategoryAssignMps_Existing_UnAssigned_ManagementPacks_Grid;
        
        /// <summary>
        /// CategoryAssignMps_UnAssigned_ManagementPacks_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_UnAssigned_ManagementPacks_Id_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_UnAssigned_ManagementPacks_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_UnAssigned_ManagementPacks_SystemName_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_UnAssigned_ManagementPacks_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_UnAssigned_ManagementPacks_PublicKey_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_UnAssigned_ManagementPacks_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryAssignMps_UnAssigned_ManagementPacks_Version_TextBox;
        
        /// <summary>
        /// CategoryAssignMps_AddMp_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryAssignMps_AddMp_Button;
        
        /// <summary>
        /// CategoryAssignMps_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CategoryAssignMps_Status;
        
        /// <summary>
        /// CategoryLocalize_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView CategoryLocalize_Page;
        
        /// <summary>
        /// CategoryLocalize_Existing_TreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTreeView CategoryLocalize_Existing_TreeView;
        
        /// <summary>
        /// CategoryLocalize_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryLocalize_Id_TextBox;
        
        /// <summary>
        /// CategoryLocalize_ParentId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryLocalize_ParentId_TextBox;
        
        /// <summary>
        /// CategoryLocalize_Name_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox CategoryLocalize_Name_TextBox;
        
        /// <summary>
        /// CategoryLocalize_Languages_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox CategoryLocalize_Languages_ComboBox;
        
        /// <summary>
        /// CategoryLocalize_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CategoryLocalize_Submit_Button;
        
        /// <summary>
        /// CategoryLocalize_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CategoryLocalize_Status;
        
        /// <summary>
        /// ManagementPackAdd_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView ManagementPackAdd_Page;
        
        /// <summary>
        /// ManagementPackAdd_Url_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAdd_Url_TextBox;
        
        /// <summary>
        /// ManagementPackAdd_Upload_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackAdd_Upload_Button;
        
        /// <summary>
        /// ManagementPackAdd_Clear_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackAdd_Clear_Button;
        
        /// <summary>
        /// ManagementPackAdd_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAdd_SystemName_TextBox;
        
        /// <summary>
        /// ManagementPackAdd_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAdd_Version_TextBox;
        
        /// <summary>
        /// ManagementPackAdd_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAdd_PublicKey_TextBox;
        
        /// <summary>
        /// ManagementPackAdd_Vendor_DropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox ManagementPackAdd_Vendor_DropDown;
        
        /// <summary>
        /// ManagementPackAdd_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackAdd_Submit_Button;
        
        /// <summary>
        /// ManagementPackAdd_TempFile_TextBox_Hidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAdd_TempFile_TextBox_Hidden;
        
        /// <summary>
        /// ManagementPackAdd_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ManagementPackAdd_Status;
        
        /// <summary>
        /// ManagementPackEdit_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView ManagementPackEdit_Page;
        
        /// <summary>
        /// ManagementPackEdit_Existing_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid ManagementPackEdit_Existing_Grid;
        
        /// <summary>
        /// ManagementPackEdit_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_Id_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_SystemName_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_PublicKey_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_Version_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_VersionIndependentGuid_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_VersionIndependentGuid_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_VendorId_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_VendorId_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_DownloadUrl_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_DownloadUrl_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_DisplayName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_DisplayName_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_Description_TextArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea ManagementPackEdit_Description_TextArea;
        
        /// <summary>
        /// ManagementPackEdit_ReleaseDate_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackEdit_ReleaseDate_TextBox;
        
        /// <summary>
        /// ManagementPackEdit_Eula_CheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ManagementPackEdit_Eula_CheckBox;
        
        /// <summary>
        /// ManagementPackEdit_Eula_TextArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea ManagementPackEdit_Eula_TextArea;
        
        /// <summary>
        /// ManagementPackEdit_Knowledge_TextArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea ManagementPackEdit_Knowledge_TextArea;
        
        /// <summary>
        /// ManagementPackEdit_Security_CheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ManagementPackEdit_Security_CheckBox;
        
        /// <summary>
        /// ManagementPackEdit_Published_CheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ManagementPackEdit_Published_CheckBox;
        
        /// <summary>
        /// ManagementPackEdit_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackEdit_Submit_Button;
        
        /// <summary>
        /// ManagementPackEdit_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ManagementPackEdit_Status;
        
        /// <summary>
        /// ManagementPackAssociate_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView ManagementPackAssociate_Page;
        
        /// <summary>
        /// ManagementPackAssociate_Existing_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid ManagementPackAssociate_Existing_Grid;
        
        /// <summary>
        /// ManagementPackAssociate_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAssociate_Id_TextBox;
        
        /// <summary>
        /// ManagementPackAssociate_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAssociate_SystemName_TextBox;
        
        /// <summary>
        /// ManagementPackAssociate_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAssociate_PublicKey_TextBox;
        
        /// <summary>
        /// ManagementPackAssociate_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackAssociate_Version_TextBox;
        
        /// <summary>
        /// ManagementPackAssociate_Associated_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox ManagementPackAssociate_Associated_ComboBox;
        
        /// <summary>
        /// ManagementPackAssociate_UnAssociate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackAssociate_UnAssociate_Button;
        
        /// <summary>
        /// ManagementPackAssociate_UnAssociated_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox ManagementPackAssociate_UnAssociated_ComboBox;
        
        /// <summary>
        /// ManagementPackAssociate_Associate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackAssociate_Associate_Button;
        
        /// <summary>
        /// ManagementPackAssociate_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ManagementPackAssociate_Status;
        
        /// <summary>
        /// ManagementPackLocalize_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView ManagementPackLocalize_Page;
        
        /// <summary>
        /// ManagementPackLocalize_Existing_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid ManagementPackLocalize_Existing_Grid;
        
        /// <summary>
        /// ManagementPackLocalize_ID_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackLocalize_ID_TextBox;
        
        /// <summary>
        /// ManagementPackLocalize_SystemName_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackLocalize_SystemName_TextBox;
        
        /// <summary>
        /// ManagementPackLocalize_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackLocalize_Version_TextBox;
        
        /// <summary>
        /// ManagementPackLocalize_PublicKey_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ManagementPackLocalize_PublicKey_TextBox;
        
        /// <summary>
        /// ManagementPackLocalize_Languages_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox ManagementPackLocalize_Languages_ComboBox;
        
        /// <summary>
        /// ManagementPackLocalize_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ManagementPackLocalize_Submit_Button;
        
        /// <summary>
        /// ManagementPackLocalize_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ManagementPackLocalize_Status;
        
        /// <summary>
        /// ProductCreate_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView ProductCreate_Page;
        
        /// <summary>
        /// ProductCreate_Name_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ProductCreate_Name_TextBox;
        
        /// <summary>
        /// ProductCreate_Version_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox ProductCreate_Version_TextBox;
        
        /// <summary>
        /// ProductCreate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ProductCreate_Button;
        
        /// <summary>
        /// ProductCreate_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ProductCreate_Status;
        
        /// <summary>
        /// ProductCreate_Existing_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid ProductCreate_Existing_Grid;
        
        /// <summary>
        /// VendorCreate_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView VendorCreate_Page;
        
        /// <summary>
        /// VendorCreate_Name_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox VendorCreate_Name_TextBox;
        
        /// <summary>
        /// VendorCreate_Link_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox VendorCreate_Link_TextBox;
        
        /// <summary>
        /// VendorCreate_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button VendorCreate_Button;
        
        /// <summary>
        /// VendorCreate_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VendorCreate_Status;
        
        /// <summary>
        /// VendorCreate_Existing_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadGrid VendorCreate_Existing_Grid;
        
        /// <summary>
        /// VendorLocalize_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView VendorLocalize_Page;
        
        /// <summary>
        /// VendorLocalize_Existing_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox VendorLocalize_Existing_ComboBox;
        
        /// <summary>
        /// VendorLocalize_Id_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox VendorLocalize_Id_TextBox;
        
        /// <summary>
        /// VendorLocalize_Name_TextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox VendorLocalize_Name_TextBox;
        
        /// <summary>
        /// VendorLocalize_Link control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadTextBox VendorLocalize_Link;
        
        /// <summary>
        /// VendorLocalize_Languages_ComboBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadComboBox VendorLocalize_Languages_ComboBox;
        
        /// <summary>
        /// VendorLocalize_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button VendorLocalize_Submit_Button;
        
        /// <summary>
        /// VendorLocalize_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label VendorLocalize_Status;
        
        /// <summary>
        /// LocalizationUpload_Page control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.PageView LocalizationUpload_Page;
        
        /// <summary>
        /// LocalizationUpload_FileUpload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.WebControls.RadUpload LocalizationUpload_FileUpload;
        
        /// <summary>
        /// LocalizationUpload_Submit_Button control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button LocalizationUpload_Submit_Button;
        
        /// <summary>
        /// LocalizationUpload_Status control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LocalizationUpload_Status;
    }
}
